var intro_data = [
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Hey",
        text:"Willkommen beim Data Dealer Demo. Bist du bereit?",
        grfx:"img/intro/start2.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        hide_db:true
    },
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Das...",
        text:"ist deine Datenbank. Bereit für Millionen hochwertige Persönlichkeitsprofile.",
        grfx:"img/intro/sammle_profile.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        show_db:true
    },
    {
        view_id:'main_view',
        x:280,
        y:520,
        title:"Der Schwarzmarkt",
        text:"Gegen ein wenig Cash liefern dir deine Kontakte erstklassige Ware.",
        grfx:"img/intro/schwarzmarkt_1.png",
        agents:['mannymayer'],
        contacts:['schwesterelfriede','stephanpetzold'],
        projects:[],
        customers:[]
    },
    {
        view_id:'main_view',
        x:180,
        y:480,
        title:"Sammle Profile",
        text:"Hol dir die neuen Profile ab und lass die Daten-Leitungen glühen.",
        grfx:"img/intro/kreislauf_1_schwarzmarkt.png",
        agents:['maraloft'],
        contacts:['onkelenzo'],
        projects:[],
        customers:[],
        contact_ready:['onkelenzo']
    },
    {
        view_id:'main_view',
        x:420,
        y:250,
        title:"Dein Imperium",
        text:"Gründe eigene Firmen und Online-Projekte.",
        grfx:"img/intro/projekte.png",
        agents:[],
        contacts:[],
        projects:['gewinnspiel','partnerboerse'],
        customers:[]
    },
    {
        view_id:'main_view',
        x:420,
        y:250,
        title:"Projekte",
        text:"Mit Gewinnspielen oder Internet-Partnerbörsen lassen sich gut Profile scheffeln.",
        grfx:"img/intro/kreislauf_2_imperium.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        project_ready:['gewinnspiel']
    },
    {
        view_id:'main_view',
        x:680,
        y:320,
        title:"Ausbauen",
        text:"Bau deine Projekte aus, mach Werbung und stell dir dein Team zusammen.",
        grfx:"img/intro/ausbauen.png",
        agents:[],
        contacts:[],
        projects:['psychotest','vorteilsclub'],
        customers:[]
    },
    {
        view_id:'main_view',
        x:750,
        y:600,
        title:"Geld Machen",
        text:"Stell deine Datenbank gegen Cash interessierten Firmen zur Verfügung.",
        grfx:"img/intro/kunden.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:['diebahn','krankenversicherung']
    },
    {
        view_id:'main_view',
        x:750,
        y:600,
        title:"Kassieren",
        text:"Mach gute Deals und lass die Kasse klingeln.",
        grfx:"img/intro/kreislauf_3_geld_machen.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:['mobilfunkdiskonter']
    },
    {
        view_id:'db_view',
        x:480,
        y:320,
        title:"Im Inneren...",
        text:"deiner Datenbank sieht es schon ganz gut gefüllt aus.",
        grfx:"img/intro/datenbank_innen.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    },
    {
        view_id:'db_view',
        x:480,
        y:320,
        title:"Neue Profile warten...",
        text:"Tipp: Wirf zuerst gleich einen Blick in deine Datenbank und schau, was zu tun ist.",
        grfx:"img/intro/get_ready.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    },
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Get Ready",
        text:"Noch Fragen? Dann wirf einen Blick in die Hilfe. Unerschrockene legen einfach los.",
        grfx:"img/intro/start.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    }
];

var levelup_data01 = [
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Gratulation!",
        text:"Du hast Level 5 erreicht.",
        grfx:"img/level_up.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        noskip:true
    },
    {
        view_id:'main_view',
        x:480,
        y:120,
        title:"Neuer Agent",
        text:"Ganz schön umtriebig! Du hast über Umwege eine neue Bekanntschaft gemacht: Dr. Ernst Krasser kennt die wichtigen Leute im Staat.",
        grfx:"img/level_up_krasser.png",
        agents:['ernstkrasser'],
        contacts:[],
        projects:[],
        customers:[],
        noskip:true
    },
    {
        view_id:'main_view',
        x:480,
        y:60,
        title:"Neue Kontakte",
        text:"Zum Einstand serviert er dir zwei seiner unzähligen Kontakte auf dem Silvertablett. Schau dir das gleich mal näher an!",
        grfx:"img/level_up_kontakte.png",
        agents:[],
        contacts:['sieglindebayerwurtz','franzsauerzapf'],
        projects:[],
        customers:[],
        noskip:true
    }
];

var token_data = [
  {
    "x": 1000,
    "y": 539,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "nachname",
    "label": "Nachname",
    "title": "Nachname",
    "stats_text": "kennst du den Nachnamen",
    "origin_stats_text": "erfährst du den Nachnamen",
    "description": "Der Nachname ist zentral für die Identifizierung einer Person. In Verbindung mit Vorname und Geburtsdatum ist das meistens schon eine ziemlich eindeutige Sache. Zugegebenermaßen nicht ganz so easy bei Müllers, Schmidts oder Schneiders.<br /><br />Vor- und Nachname gehören gemeinsam mit dem Geburtsdatum zu den Schlüssel-Eigenschaften in deiner Datenbank! Wenn du neue Profile bekommst, kann sie deine Datenbank damit möglicherweise bereits vorhandenen Profilen zuordnen.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/nachname_s1.png",
    "sprite_img": "img/tokens/nachname_s1.png",
    "tokenset_img": "img/tokens/tokens_set/nachname_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/nachname-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/nachname-hover_s1.png",
    "sprite_img_down": "img/tokens/nachname-down_s1.png",
    "sprite_img_hover": "img/tokens/nachname-hover_s1.png",
    "sprite_img_drag": "img/tokens/nachname-drag_s1.png"
  },
  {
    "x": 766,
    "y": 532,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "adresse",
    "label": "Adresse",
    "title": "Adresse",
    "stats_text": "kennst du Straße und Hausnummer",
    "origin_stats_text": "erfährst du Straße und Hausnummer",
    "description": "Die Wohnadresse eignet sich nicht nur hervorragend zum Zumüllen mit Werbeprospekten, sondern sagt auch sonst einiges über die Person aus. Luxusviertel oder Problembezirk? Großstadt-Ratte oder Land-Ei? In Kombination mit anderen Infos sehr wichtig beim professionellen Einordnen und Schubladisieren.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/adresse_s1.png",
    "sprite_img": "img/tokens/adresse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/adresse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/adresse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/adresse-hover_s1.png",
    "sprite_img_down": "img/tokens/adresse-down_s1.png",
    "sprite_img_hover": "img/tokens/adresse-hover_s1.png",
    "sprite_img_drag": "img/tokens/adresse-drag_s1.png"
  },
  {
    "x": 893,
    "y": 622,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "wohnort",
    "label": "Wohnort",
    "title": "Wohnort",
    "stats_text": "kennst du Wohnort und Postleitzahl",
    "origin_stats_text": "erfährst du Wohnort und Postleitzahl",
    "description": "Abgesehen davon, dass der Wohnort dabei hilft, jemand eindeutig zu identifizieren, sagt er auch sonst einiges über die Person aus. Luxusviertel oder Problembezirk? Großstadt-Ratte oder Land-Ei? In Kombination mit anderen Infos sehr wichtig beim professionellen Einordnen und Schubladisieren.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/wohnort_s1.png",
    "sprite_img": "img/tokens/wohnort_s1.png",
    "tokenset_img": "img/tokens/tokens_set/wohnort_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/wohnort-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/wohnort-hover_s1.png",
    "sprite_img_down": "img/tokens/wohnort-down_s1.png",
    "sprite_img_hover": "img/tokens/wohnort-hover_s1.png",
    "sprite_img_drag": "img/tokens/wohnort-drag_s1.png"
  },
  {
    "x": 912,
    "y": 770,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "telefonnummer",
    "label": "Telefonnummer",
    "title": "Telefonnummer",
    "stats_text": "kennst du ein oder mehrere Telefonnummern",
    "origin_stats_text": "erfährst du ein oder mehrere Telefonnummern",
    "description": "Das Telefon ist eines der wichtigesten persönlichen Kommunikations-Tools. Werbeagenturen zahlen gut für Profile mit Telefonnummer. <br /><br />Außerdem ballen sich im Zeitalter der Smartphones immer mehr persönliche Informationen in diesem ständigen Begleiter. Hast du Zugriff auf das Mobiltelefon, weißt du beinahe alles über den Besitzer. Aus den darin gespeicherten Daten lassen sich perfekte Persönlichkeitsprofile erstellen. Besonders fiese Datensammler schieben den Leuten lustige Apps unter, die still und heimlich den Smartphone-Speicher anzapfen.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/telefonnummer_s1.png",
    "sprite_img": "img/tokens/telefonnummer_s1.png",
    "tokenset_img": "img/tokens/tokens_set/telefonnummer_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/telefonnummer-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/telefonnummer-hover_s1.png",
    "sprite_img_down": "img/tokens/telefonnummer-down_s1.png",
    "sprite_img_hover": "img/tokens/telefonnummer-hover_s1.png",
    "sprite_img_drag": "img/tokens/telefonnummer-drag_s1.png"
  },
  {
    "x": 782,
    "y": 673,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "geburtsdatum",
    "label": "Geburtsdatum",
    "title": "Geburtsdatum",
    "stats_text": "kennst du das Geburtsdatum",
    "origin_stats_text": "erfährst du das Geburtsdatum",
    "description": "Die Kombination aus Name und Geburtsdatum identifiziert eine Person ziemlich eindeutig. Darüber hinaus ergibt sich aus dem Geburtsdatum das Alter, und daraus lässt sich auf vieles rückschließen. Etwa auf Vermögen, Einkommen, Interessen, Probleme, Konsumgewohnheiten oder Gesundheitszustand.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/geburtsdatum_s1.png",
    "sprite_img": "img/tokens/geburtsdatum_s1.png",
    "tokenset_img": "img/tokens/tokens_set/geburtsdatum_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/geburtsdatum-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/geburtsdatum-hover_s1.png",
    "sprite_img_down": "img/tokens/geburtsdatum-down_s1.png",
    "sprite_img_hover": "img/tokens/geburtsdatum-hover_s1.png",
    "sprite_img_drag": "img/tokens/geburtsdatum-drag_s1.png"
  },
  {
    "x": 1116,
    "y": 599,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "geschlecht",
    "label": "Geschlecht",
    "title": "Geschlecht",
    "stats_text": "weißt du, ob männlich oder weiblich",
    "origin_stats_text": "erfährst du, ob männlich oder weiblich",
    "description": "Der Eintrag \"Geschlecht\" in Geburtsurkunde und Reisepass ist zwar Gott sei Dank schon lang nicht mehr so bestimmend fürs Leben, wie das schon mal war. Männleins und Weibleins stehen aber immer noch ganz schön hilflos unter der Knute der für sie vorgesehenen Geschlechterrollen. Unterschiedliche Einkommen, Interessen, Probleme, Konsumgewohnheiten, Lebenserwartungen - das Geschlecht einer Person zu kennen bietet dir in der Praxis viele Möglichkeiten.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/geschlecht_s1.png",
    "sprite_img": "img/tokens/geschlecht_s1.png",
    "tokenset_img": "img/tokens/tokens_set/geschlecht_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/geschlecht-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/geschlecht-hover_s1.png",
    "sprite_img_down": "img/tokens/geschlecht-down_s1.png",
    "sprite_img_hover": "img/tokens/geschlecht-hover_s1.png",
    "sprite_img_drag": "img/tokens/geschlecht-drag_s1.png"
  },
  {
    "x": 1018,
    "y": 696,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "email",
    "label": "Email",
    "title": "Email",
    "stats_text": "kennst du ein oder mehrere Email-Adressen",
    "origin_stats_text": "erfährst du ein oder mehrere Email-Adressen",
    "description": "Die Email-Adresse ist heute wichtiger als die Postadresse und der Schlüssel zu vielen Daten-Goldgruben im Internet. Es gibt unzählige Online-Services, bei denen sich Nutzer und Nutzerinnen nicht etwa mit ihrem Namen, sondern einzig mit ihrer Email-Adresse anmelden. Sobald du die Email-Adresse einer Person kennst, kannst du sie immer wieder zielgenau identifizieren - egal unter welchem Nickname oder Pseudonym jemand gerade unterwegs ist. Außerdem kannst du Email-Adressen natürlich hervorragend für Werbezwecke verkaufen.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/email_s1.png",
    "sprite_img": "img/tokens/email_s1.png",
    "tokenset_img": "img/tokens/tokens_set/email_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/email-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/email-hover_s1.png",
    "sprite_img_down": "img/tokens/email-down_s1.png",
    "sprite_img_hover": "img/tokens/email-hover_s1.png",
    "sprite_img_drag": "img/tokens/email-drag_s1.png"
  },
  {
    "x": 430,
    "y": 456,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "personalakten",
    "label": "Personal\nakten",
    "title": "Personalakten",
    "stats_text": "hast du unternehmensinterne Personalakten in der Datenbank",
    "origin_stats_text": "erhältst du firmeninterne Personalakten",
    "description": "Notorisches Zu-Spät-Kommen? Krankfeiern? Dauerndes rummotzen? Sonstige Verwarnungen? Viele Firmen legen ausführliche Dossiers über ihre Mitarbeiter mit all ihren Stärken, Schwächen und Verfehlungen an. Darin werden mehr oder weniger legal ganz schön viele Details gespeichert. Sehr interessant für zukünftige Arbeitgeber.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/personalakten_s1.png",
    "sprite_img": "img/tokens/personalakten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/personalakten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/personalakten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/personalakten-hover_s1.png",
    "sprite_img_down": "img/tokens/personalakten-down_s1.png",
    "sprite_img_hover": "img/tokens/personalakten-hover_s1.png",
    "sprite_img_drag": "img/tokens/personalakten-drag_s1.png"
  },
  {
    "x": 464,
    "y": 618,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "lebenslauf",
    "label": "Lebenslauf",
    "title": "Lebenslauf",
    "stats_text": "weißt du Schulbildung, Studien, Jobs, Arbeitslosigkeit und mehr",
    "origin_stats_text": "erfährst du Schulbildung, Studien, Jobs, Arbeitslosigkeit und mehr",
    "description": "Für viele Jobs ist ein perfekter Lebenslauf ein absolutes Muss. Möglichst lückenlos soll er sein, jede Lebens-Station stimmig erklärbar. Die Unternehmen verlassen sich dabei ungern auf die Angaben in den Bewerbungen. Zu groß ist oft die Versuchung, im Lebenslauf da und dort ein wenig kosmetisch nachzubessern.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/lebenslauf_s1.png",
    "sprite_img": "img/tokens/lebenslauf_s1.png",
    "tokenset_img": "img/tokens/tokens_set/lebenslauf_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/lebenslauf-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/lebenslauf-hover_s1.png",
    "sprite_img_down": "img/tokens/lebenslauf-down_s1.png",
    "sprite_img_hover": "img/tokens/lebenslauf-hover_s1.png",
    "sprite_img_drag": "img/tokens/lebenslauf-drag_s1.png"
  },
  {
    "x": 884,
    "y": 479,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "vorname",
    "label": "Vorname",
    "title": "Vorname",
    "stats_text": "kennst du den Vornamen",
    "origin_stats_text": "erfährst du den Vornamen",
    "description": "Ob bescheuert oder cool, kurz oder lang, altmodisch oder hip - der Vorname ist zentral für die eindeutige Identifizierung einer Person und damit eine wichtige Basis-Eigenschaft in deinem Business. Dazu lässt sich zumindest im deutschen Sprachraum ziemlich eindeutig vom Vornamen auf das Geschlecht schließen. Mit Hilfe von Listen beliebter Vornamen verschiedener Geburtsjahrgänge kannst du sogar ungefähr das Alter einer Person einschätzen. Ein Thoralf oder eine Hildegard sind wohl kaum unter 30, ein Kevin oder eine Mandy dagegen selten über 50.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/vorname_s1.png",
    "sprite_img": "img/tokens/vorname_s1.png",
    "tokenset_img": "img/tokens/tokens_set/vorname_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/vorname-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/vorname-hover_s1.png",
    "sprite_img_down": "img/tokens/vorname-down_s1.png",
    "sprite_img_hover": "img/tokens/vorname-hover_s1.png",
    "sprite_img_drag": "img/tokens/vorname-drag_s1.png"
  },
  {
    "x": 601,
    "y": 651,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "besuchteschulen",
    "label": "Besuchte\nSchulen",
    "title": "Besuchte Schulen",
    "stats_text": "weißt du, welche Schulen von wann bis wann besucht wurden",
    "origin_stats_text": "erfährst du, welche Schulen von wann bis wann besucht wurden",
    "description": "Promis protzen manchmal in den Medien mit abgebrochenen Schullaufbahnen und schlechten Noten. Für eine Berufslaufbahn als Prominenter ist das wohl auch kein Problem. In der harten Realität sieht das allerdings anders aus. Vor allem bei jüngeren ist ein lückenloser Werdegang in guten Schulen immer noch absolute Voraussetzung für einen Job. Außerdem wird in Bewerbungsschreiben gern mal geflunkert.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/besuchteschulen_s1.png",
    "sprite_img": "img/tokens/besuchteschulen_s1.png",
    "tokenset_img": "img/tokens/tokens_set/besuchteschulen_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/besuchteschulen-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/besuchteschulen-hover_s1.png",
    "sprite_img_down": "img/tokens/besuchteschulen-down_s1.png",
    "sprite_img_hover": "img/tokens/besuchteschulen-hover_s1.png",
    "sprite_img_drag": "img/tokens/besuchteschulen-drag_s1.png"
  },
  {
    "x": 839,
    "y": 298,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "einkommen",
    "label": "Einkommen",
    "title": "Einkommen",
    "stats_text": "weißt du, wieviel sie monatlich aufs Konto bekommen",
    "origin_stats_text": "erfährst du, wieviel sie monatlich aufs Konto bekommen",
    "description": "Höchstverdiener, Mittelklasse oder hart an der Armutsgrenze? Ob das fair ist oder nicht, interessiert uns nicht. Keine Frage: Die Leute verdienen sehr unterschiedlich - das prägt ihr ganzes Leben und meistens auch das ihrer Kinder. Ob Unternehmerlohn, Sklavenjob, Arbeitslosengeld, Pension oder Unterstützung durch die Familie - für die finanzielle Situation ihrer Kunden interessieren sich viele.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/einkommen_s1.png",
    "sprite_img": "img/tokens/einkommen_s1.png",
    "tokenset_img": "img/tokens/tokens_set/einkommen_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/einkommen-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/einkommen-hover_s1.png",
    "sprite_img_down": "img/tokens/einkommen-down_s1.png",
    "sprite_img_hover": "img/tokens/einkommen-hover_s1.png",
    "sprite_img_drag": "img/tokens/einkommen-drag_s1.png"
  },
  {
    "x": 685,
    "y": 257,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "schulden",
    "label": "Schulden \nund Kredite",
    "title": "Schulden und Kredite",
    "stats_text": "weißt du, ob sie verschuldet sind und wenn ja, wie desaströs",
    "origin_stats_text": "erfährst du, ob sie verschuldet sind und wenn ja, wie desaströs",
    "description": "Ob Ratenzahlung für den Protze-Fernseher, Auto-Leasing oder gar der fette Häuslbauerkredit: Viele Leute sind verschuldet. Besonders heikel, wenn ein Kredit für die Rückzahlung eines anderen Kredits aufgenommen wurde. Was für Staaten und Konzerne ganz normal ist, geht bei Privatpersonen gar  nicht! Sind die Schulden im Verhältnis zu Einkommen und Einkäufen, landen die Leute auf der schwarzen Liste und niemand will mehr Geschäfte mit ihnen machen. Besonders interessant für Banken, Versandhäuser, Online-Shops und etwa Mobilfunk-Anbieter.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/schulden_s1.png",
    "sprite_img": "img/tokens/schulden_s1.png",
    "tokenset_img": "img/tokens/tokens_set/schulden_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/schulden-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/schulden-hover_s1.png",
    "sprite_img_down": "img/tokens/schulden-down_s1.png",
    "sprite_img_hover": "img/tokens/schulden-hover_s1.png",
    "sprite_img_drag": "img/tokens/schulden-drag_s1.png"
  },
  {
    "x": 1168,
    "y": 445,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "konsumgewohnheiten",
    "label": "Konsum-\ngewohnheiten",
    "title": "Konsumgewohnheiten",
    "stats_text": "weißt du, welche Produkte und Marken sie regelmäßig kaufen",
    "origin_stats_text": "erfährst du, welche Produkte und Marken sie regelmäßig kaufen",
    "description": "Lebensmittel, Getränke, Kosmetika, Kleidung, Schuhe, Elektrogeräte, Tonträger, Videos, Bücher, Zeitschriften oder Autos: Wenn du über ein paar Monate eine detaillierte Liste persönlicher Einkäufe durchsiehst, kennst du diese Person ganz gut. Allein aus den Supermarkt-Einkäufen kannst du ganz gut abschätzen, ob jemand reich oder arm ist oder gebildet oder ungebildet. Und vielleicht sogar, ob schwul oder hetero. Wenn du große Mengen an Konsumprofilen besitzt, kann das deine hochintelligente Datenbank-Maschine natürlich noch viel besser analysieren. Lässt sich super verkaufen - nicht nur für gezielte Werbung.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/konsumgewohnheiten_s1.png",
    "sprite_img": "img/tokens/konsumgewohnheiten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/konsumgewohnheiten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/konsumgewohnheiten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/konsumgewohnheiten-hover_s1.png",
    "sprite_img_down": "img/tokens/konsumgewohnheiten-down_s1.png",
    "sprite_img_hover": "img/tokens/konsumgewohnheiten-hover_s1.png",
    "sprite_img_drag": "img/tokens/konsumgewohnheiten-drag_s1.png"
  },
  {
    "x": 1169,
    "y": 288,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "bevorzugtecomputergames",
    "label": "Bevorzugte\nComputer-Games",
    "title": "Bevorzugte Computer-Games",
    "stats_text": "weißt du, welche Art von Computer-Games sie bevorzugen",
    "origin_stats_text": "erfährst du, welche Art von Computer-Games sie bevorzugen",
    "description": "Casual-Games, Strategie, Online-Rollenspiele oder blutrünstige Ego-Shooter? Manche behaupten ja, von den bevorzugten Computer-Games ließe sich auf den Charakter rückschließen. Das ist zwar umstritten, den Glauben wollen wir ihnen aber auf keinen Fall nehmen und geben ihnen, was sie wollen. Für Cash!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/bevorzugtecomputergames_s1.png",
    "sprite_img": "img/tokens/bevorzugtecomputergames_s1.png",
    "tokenset_img": "img/tokens/tokens_set/bevorzugtecomputergames_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/bevorzugtecomputergames-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/bevorzugtecomputergames-hover_s1.png",
    "sprite_img_down": "img/tokens/bevorzugtecomputergames-down_s1.png",
    "sprite_img_hover": "img/tokens/bevorzugtecomputergames-hover_s1.png",
    "sprite_img_drag": "img/tokens/bevorzugtecomputergames-drag_s1.png"
  },
  {
    "x": 686,
    "y": 402,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "gewicht",
    "label": "Gewicht",
    "title": "Gewicht",
    "stats_text": "kennst du das aktuelle Körpergewicht",
    "origin_stats_text": "erfährst du das aktuelle Körpergewicht",
    "description": "Magersüchtig, voll fett oder eh okay? Übergewichtige Menschen haben es zwar schwer genug, und an die retuschierten Models aus der Werbung kommt eh niemand ran. Aber sorry, Leute: aber wer aus der Norm fällt, ist halt oft unerwünscht. Das Gewicht ist eine lukrative Information für alle, die mit Gesundheit zu tun haben. Und auch für manche Arbeitgeber nicht ganz uninteressant. Ganz zu schweigen von gezielter Produktwerbung für Dicke!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/gewicht_s1.png",
    "sprite_img": "img/tokens/gewicht_s1.png",
    "tokenset_img": "img/tokens/tokens_set/gewicht_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/gewicht-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/gewicht-hover_s1.png",
    "sprite_img_down": "img/tokens/gewicht-down_s1.png",
    "sprite_img_hover": "img/tokens/gewicht-hover_s1.png",
    "sprite_img_drag": "img/tokens/gewicht-drag_s1.png"
  },
  {
    "x": 572,
    "y": 489,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "koerpergroesse",
    "label": "Körpergrösse",
    "title": "Körpergrösse",
    "stats_text": "kennst du die Körpergröße",
    "origin_stats_text": "erfährst du die Körpergröße",
    "description": "Hauptsächlich in Verbindung mit dem Körpergewicht interessant. Aus Größe und Gewicht lässt sich der Body-Mass-Index errechnen, kurz BMI. Der ist um einiges aussagekräftiger als das Gewicht allein und lässt sich daher noch viel besser verkaufen. In vielen Jobs haben Fettsäcke keine Chance und die Krankenversicherungen verzichten gerne auf potenzielle Risikopatienten.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/koerpergroesse_s1.png",
    "sprite_img": "img/tokens/koerpergroesse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/koerpergroesse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/koerpergroesse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/koerpergroesse-hover_s1.png",
    "sprite_img_down": "img/tokens/koerpergroesse-down_s1.png",
    "sprite_img_hover": "img/tokens/koerpergroesse-hover_s1.png",
    "sprite_img_drag": "img/tokens/koerpergroesse-drag_s1.png"
  },
  {
    "x": 1015,
    "y": 308,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "ernaehrungsweise",
    "label": "Ernährungs\nverhalten",
    "title": "Ernährungsverhalten",
    "stats_text": "weißt du, was sie täglich in sich reinstopfen",
    "origin_stats_text": "erfährst du, was sie täglich in sich reinstopfen",
    "description": "Raue Mengen an Fleisch oder hauptsächlich vegetarisch? Chips, Cola und jeden Tag Tiefkühlkost oder Bio, leicht und mit viel Gemüse? Aus einer Liste der Einkäufe lassen sich Ernährungsprofile erstellen, aus denen sich mit einer gewissen Sicherheit auf Gesundheitszustand und -Prognose schließen lässt. Der erfasste Zeitraum muss gar nicht mal so lang sein, ein paar Wochen genügen in der Regel.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/ernaehrungsweise_s1.png",
    "sprite_img": "img/tokens/ernaehrungsweise_s1.png",
    "tokenset_img": "img/tokens/tokens_set/ernaehrungsweise_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/ernaehrungsweise-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/ernaehrungsweise-hover_s1.png",
    "sprite_img_down": "img/tokens/ernaehrungsweise-down_s1.png",
    "sprite_img_hover": "img/tokens/ernaehrungsweise-hover_s1.png",
    "sprite_img_drag": "img/tokens/ernaehrungsweise-drag_s1.png"
  },
  {
    "x": 726,
    "y": 820,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "krankenakte",
    "label": "Krankenakten",
    "title": "Krankenakten",
    "stats_text": "hast du mehr oder weniger ausführliche Krankenakten in der Datenbank",
    "origin_stats_text": "bekommst du mehr oder weniger ausführliche Krankenakten",
    "description": "Vergangene und aktuelle Krankheiten, Behandlungen und Operationen, Untersuchungsbefunde und deren Zeitpunkte: Krankenakten aus Arztpraxen und Kliniken bieten wertvolle Anhaltspunkte für zukünftige Prognosen. Solche Infos lässt sich die Gesundheitsindustrie viel kosten.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/krankenakte_s1.png",
    "sprite_img": "img/tokens/krankenakte_s1.png",
    "tokenset_img": "img/tokens/tokens_set/krankenakte_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/krankenakte-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/krankenakte-hover_s1.png",
    "sprite_img_down": "img/tokens/krankenakte-down_s1.png",
    "sprite_img_hover": "img/tokens/krankenakte-hover_s1.png",
    "sprite_img_drag": "img/tokens/krankenakte-drag_s1.png"
  },
  {
    "x": 874,
    "y": 936,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "chronischekrankheiten",
    "label": "Chronische\nKrankheiten",
    "title": "Chronische Krankheiten",
    "stats_text": "weißt du, ob und welche chronischen Erkrankungen vorliegen",
    "origin_stats_text": "erfährst du, ob und welche chronischen Erkrankungen vorliegen",
    "description": "Asthma, Migräne, Allergien, Neurodermitis oder chronische Bandscheibenprobleme? Suchtkrankheiten, Depressionen, Hepatitis oder gar Multiple Sklerose oder Krebs? Krankenversicherungen interessieren sich brennend dafür, und auch so mancher Arbeitgeber sagt nicht Nein zu diesen Infos.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/chronischekrankheiten_s1.png",
    "sprite_img": "img/tokens/chronischekrankheiten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/chronischekrankheiten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/chronischekrankheiten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/chronischekrankheiten-hover_s1.png",
    "sprite_img_down": "img/tokens/chronischekrankheiten-down_s1.png",
    "sprite_img_hover": "img/tokens/chronischekrankheiten-hover_s1.png",
    "sprite_img_drag": "img/tokens/chronischekrankheiten-drag_s1.png"
  },
  {
    "x": 1039,
    "y": 921,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "anzahldersolarienbesuche",
    "label": "Solarien-\nBesuche",
    "title": "Solarien-Besuche",
    "stats_text": "weißt du, wie viel UV-Strahlung sie abbekommen haben",
    "origin_stats_text": "erfährst du, wie viel UV-Strahlung sie abbekommen haben",
    "description": "Jede Woche 20 Minuten künstliche Sonne mit der stärksten Strahlenkanone der Filiale? Wenn das der Hautarzt wüsste! Auf Dauer tut das wohl nicht so gut, irgendwann machen sich vielleicht irgendwelche Muttermale selbstständig und wachsen sich zu so ganz und gar nicht geilen Melanomen aus. Das werden die Betroffenen schon noch merken, es gibt aber auch noch andere, die sich für den legeren Umgang mit der UV-Strahlung interessieren. Denn für die Gesundheitsindustrie besteht die Welt hauptsächlich aus Risikofaktoren.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/anzahldersolarienbesuche_s1.png",
    "sprite_img": "img/tokens/anzahldersolarienbesuche_s1.png",
    "tokenset_img": "img/tokens/tokens_set/anzahldersolarienbesuche_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/anzahldersolarienbesuche-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/anzahldersolarienbesuche-hover_s1.png",
    "sprite_img_down": "img/tokens/anzahldersolarienbesuche-down_s1.png",
    "sprite_img_hover": "img/tokens/anzahldersolarienbesuche-hover_s1.png",
    "sprite_img_drag": "img/tokens/anzahldersolarienbesuche-drag_s1.png"
  },
  {
    "x": 1389,
    "y": 622,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "alterbeimerstenmal",
    "label": "Alter beim\n\"ersten Mal\"",
    "title": "Alter beim \"ersten Mal\"",
    "stats_text": "weißt du, mit welchem Alter sie das erste Mal gefickt haben",
    "origin_stats_text": "erfährst du, mit welchem Alter sie das erste Mal gefickt haben",
    "description": "Na, das ist ja mal ein pikantes kleines Detail. Und doch für dein Persönlichkeitsprofil verwertbar. Zu früh die Unschuld verloren? Neigt wohl zu unüberlegtem, riskantem Verhalten und ist leicht beeinflussbar! Viel zu spät? Seltsamer Typ! Im \"großen psychologischen Matching-Test\" bei der Online-Partnerbörse erfährst du natürlich noch viel mehr als das. Schön, dass die Leute nie die langen \"Erklärungen zur Privatsphäre\" lesen.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/alterbeimerstenmal_s1.png",
    "sprite_img": "img/tokens/alterbeimerstenmal_s1.png",
    "tokenset_img": "img/tokens/tokens_set/alterbeimerstenmal_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/alterbeimerstenmal-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/alterbeimerstenmal-hover_s1.png",
    "sprite_img_down": "img/tokens/alterbeimerstenmal-down_s1.png",
    "sprite_img_hover": "img/tokens/alterbeimerstenmal-hover_s1.png",
    "sprite_img_drag": "img/tokens/alterbeimerstenmal-drag_s1.png"
  },
  {
    "x": 1222,
    "y": 737,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "sexuelleorientierung",
    "label": "Sexuelle\nOrientierung",
    "title": "Sexuelle Orientierung",
    "stats_text": "weißt du, ob hetero, schwul, lesbisch oder sonstwas",
    "origin_stats_text": "erfährst du, ob hetero, schwul, lesbisch oder sonstwas",
    "description": "Nicht-Heteros haben es zwar nicht mehr ganz so schwer wie früher mal. Trotzdem gibts immer noch jede Menge Steinzeit-Menschen, die ein Problem mit bestimmten sexuellen Orientierungen haben. Darum halten manche ihre Neigungen vor Eltern oder Arbeitgebern geheim. Aber nicht vor dir! Die sexuelle Orientierung lässt sich gut für zielgruppenspezifische Werbung einsetzen, ist aber auch darüber hinaus für ein vollständiges Persönlichkeitsprofil unerlässlich.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/sexuelleorientierung_s1.png",
    "sprite_img": "img/tokens/sexuelleorientierung_s1.png",
    "tokenset_img": "img/tokens/tokens_set/sexuelleorientierung_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/sexuelleorientierung-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/sexuelleorientierung-hover_s1.png",
    "sprite_img_down": "img/tokens/sexuelleorientierung-down_s1.png",
    "sprite_img_hover": "img/tokens/sexuelleorientierung-hover_s1.png",
    "sprite_img_drag": "img/tokens/sexuelleorientierung-drag_s1.png"
  },
  {
    "x": 1266,
    "y": 592,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "beziehungsstatus",
    "label": "Beziehungsstatus",
    "title": "Beziehungsstatus",
    "stats_text": "weißt du, wie kompliziert es ist",
    "origin_stats_text": "erfährst du, wie kompliziert es ist",
    "description": "Single, liiert oder gar verheiratet, geschieden, verwitwet? Singles sind oft flexibler, Pärchen dafür stabiler. Das kann sich heute zwar schnell ändern, lässt sich aber trotzdem gut einsetzen - egal ob für Werbung oder ganz allgemein zur Erstellung umfassender Persönlichkeitsprofile.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/beziehungsstatus_s1.png",
    "sprite_img": "img/tokens/beziehungsstatus_s1.png",
    "tokenset_img": "img/tokens/tokens_set/beziehungsstatus_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/beziehungsstatus-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/beziehungsstatus-hover_s1.png",
    "sprite_img_down": "img/tokens/beziehungsstatus-down_s1.png",
    "sprite_img_hover": "img/tokens/beziehungsstatus-hover_s1.png",
    "sprite_img_drag": "img/tokens/beziehungsstatus-drag_s1.png"
  },
  {
    "x": 1318,
    "y": 923,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "partyfotos",
    "label": "Party-Fotos",
    "title": "Party-Fotos",
    "stats_text": "hast du lustige Party-Fotos in der Datenbank",
    "origin_stats_text": "bekommst du lustige Party-Fotos",
    "description": "Die Leute sind ja so süß. Vor allem die Teenies. Wie die es lieben, auch noch die seltsamsten Fotos möglichst öffentlich zu machen! Jedes lustige Handyfoto wird gleich mal online gestellt und wenn man das nicht selber macht, wird das von den geschätzten Freunde oder von einem Fotograf des Partyfoto-Portals erledigt. Wobei hier schon betont werden soll: Nicht jeder Arbeitgeber stört sich an dem Foto mit dem halb nackten, grölenden Alkohol-Zombie von der Party vom letzten Monat! Aber er will es zumindest gesehen haben.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/partyfotos_s1.png",
    "sprite_img": "img/tokens/partyfotos_s1.png",
    "tokenset_img": "img/tokens/tokens_set/partyfotos_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/partyfotos-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/partyfotos-hover_s1.png",
    "sprite_img_down": "img/tokens/partyfotos-down_s1.png",
    "sprite_img_hover": "img/tokens/partyfotos-hover_s1.png",
    "sprite_img_drag": "img/tokens/partyfotos-drag_s1.png"
  },
  {
    "x": 413,
    "y": 807,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "vertrauenswuerdigoderunzuverlaessig",
    "label": "Vertrauenswürdig/\nUnzuverlässig?",
    "title": "Vertrauenswürdig oder Unzuverlässig?",
    "stats_text": "weißt du, wie loyal und zuverlässig sie sind",
    "origin_stats_text": "erfährst du, wie loyal und zuverlässig sie sind",
    "description": "Kann man sich auf die Person verlassen oder haben wir es hier mit einem echt unzuverlässigen Arschloch zu tun? Das fragen sich viele Arbeitgeber beim Bewerbungsgespräch. Das Gespräch ist kurz, eigentlich wär hier eine zuverlässige Einschätzung gefragt. Durch kleine Tricks wie etwa einem Online-Psychotest kannst du hier Abhilfe schaffen. Eine gewisse Fehlerrate ist unvermeidlich, aber besser als nichts!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "sprite_img": "img/tokens/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "tokenset_img": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig-hover_s1.png",
    "sprite_img_down": "img/tokens/vertrauenswuerdigoderunzuverlaessig-down_s1.png",
    "sprite_img_hover": "img/tokens/vertrauenswuerdigoderunzuverlaessig-hover_s1.png",
    "sprite_img_drag": "img/tokens/vertrauenswuerdigoderunzuverlaessig-drag_s1.png"
  },
  {
    "x": 539,
    "y": 781,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "zufriedenoderfrustriert",
    "label": "Zufrieden/\nFrustriert?",
    "title": "Zufrieden oder Frustriert?",
    "stats_text": "weißt du, ob sie eher zufrieden oder frustriert sind",
    "origin_stats_text": "erfährst du, ob sie eher zufrieden oder frustriert sind",
    "description": "Im Großen und Ganzen glücklich? Oder doch ziemlich unzufrieden und frustriert? Es gibt verschiedene Methoden, Menschen psychologisch zu scannen. Wenn du mit der Tür ins Haus fällst, wirst du kaum was erfahren. Wenn du es aber geschickt und trickreich anstellst, verraten dir die Leute mit Begeisterung ihre intimen seelischen Zustände. Charakterliche Einschätzungen wie diese bilden eine wertvolle Basis für die fundierte Analyse einer Person.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/zufriedenoderfrustriert_s1.png",
    "sprite_img": "img/tokens/zufriedenoderfrustriert_s1.png",
    "tokenset_img": "img/tokens/tokens_set/zufriedenoderfrustriert_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/zufriedenoderfrustriert-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/zufriedenoderfrustriert-hover_s1.png",
    "sprite_img_down": "img/tokens/zufriedenoderfrustriert-down_s1.png",
    "sprite_img_hover": "img/tokens/zufriedenoderfrustriert-hover_s1.png",
    "sprite_img_drag": "img/tokens/zufriedenoderfrustriert-drag_s1.png"
  },
  {
    "x": 561,
    "y": 924,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "iq",
    "label": "IQ",
    "title": "IQ",
    "stats_text": "kennst du den sogenannten Intelligenzquotienten",
    "origin_stats_text": "erfährst du den sogenannten Intelligenzquotienten",
    "description": "Ob der IQ wirklich dazu geeignet ist, die Intelligenz zu messen, darüber streitet die Psychologie seit Jahrzehnten. Nichtsdestotrotz stehen die Leute unglaublich auf IQ-Tests und kein Arbeitgeber würde wohl ein derartiges Testergebnis ablehnen. Einfach so als Hintergrund-Information.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/iq_s1.png",
    "sprite_img": "img/tokens/iq_s1.png",
    "tokenset_img": "img/tokens/tokens_set/iq_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/iq-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/iq-hover_s1.png",
    "sprite_img_down": "img/tokens/iq-down_s1.png",
    "sprite_img_hover": "img/tokens/iq-hover_s1.png",
    "sprite_img_drag": "img/tokens/iq-drag_s1.png"
  },
  {
    "x": 1377,
    "y": 778,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "passwoerter",
    "label": "Passwörter",
    "title": "Passwörter",
    "stats_text": "kennst du ein oder mehrere Passwörter",
    "origin_stats_text": "erfährst du ein oder mehrere Passwörter",
    "description": "Fremde Passwörter in deiner Datenbank? Ganz schön heikel. Aber wer weiß, vielleicht kannst du später mal was damit anfangen. Zur \"Sicherheit\" einfach mal abspeichern! Eventuell kannst du damit User irgendwelcher Online-Portale wiedererkennen, obwohl sie Pseudonyme und anonyme Email-Adressen verwenden.<br /><br />Und falls du mal so richtig in Cash-Nöten bist, gibts finstere Gegenden am Daten-Markt, die auch an heiklen Angelegenheiten interessiert sind.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/passwoerter_s1.png",
    "sprite_img": "img/tokens/passwoerter_s1.png",
    "tokenset_img": "img/tokens/tokens_set/passwoerter_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/passwoerter-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/passwoerter-hover_s1.png",
    "sprite_img_down": "img/tokens/passwoerter-down_s1.png",
    "sprite_img_hover": "img/tokens/passwoerter-hover_s1.png",
    "sprite_img_drag": "img/tokens/passwoerter-drag_s1.png"
  },
  {
    "x": 522,
    "y": 326,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "kreditkartennummer",
    "label": "Kreditkarten\nnummer",
    "title": "Kreditkartennummer",
    "stats_text": "kennst du die Kreditkartennummer",
    "origin_stats_text": "erfährst du die Kreditkartennummer",
    "description": "Kreditkarten sind super. Sobald dieses beliebte Online-Zahlungsmittel ins Spiel kommt, hast du gewonnen. Denn in diesem Fall kannst du sicher sein, dass du ziemlich zuverlässige Angaben zur Person geliefert bekommst.<br /><br />Ganz abgesehen davon, dass der illegale Handel mit Kreditkartennummern floriert. Ob du dich darauf einlässt, solltest du dir drei Mal überlegen.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/kreditkartennummer_s1.png",
    "sprite_img": "img/tokens/kreditkartennummer_s1.png",
    "tokenset_img": "img/tokens/tokens_set/kreditkartennummer_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/kreditkartennummer-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/kreditkartennummer-hover_s1.png",
    "sprite_img_down": "img/tokens/kreditkartennummer-down_s1.png",
    "sprite_img_hover": "img/tokens/kreditkartennummer-hover_s1.png",
    "sprite_img_drag": "img/tokens/kreditkartennummer-drag_s1.png"
  },
  {
    "x": 1192,
    "y": 878,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "ipadresse",
    "label": "IP-Adresse",
    "title": "IP-Adresse",
    "stats_text": "kennst du eine oder mehrere IP-Adressen",
    "origin_stats_text": "erfährst du eine oder mehrere IP-Adressen",
    "description": "Ob Computer, Spielkonsole oder Smartphone mit Internet-Zugang - jedes Gerät, das mit dem Netz verbunden ist, besitzt eine eigene IP-Adresse. Die UserInnen hinterlassen damit auch dann ihre Spuren beim Surfen, wenn sie ohne jede Registrierung herumsurfen. <br /><br />Zwar teilen sich manchmal mehrere Personen eines Haushalts eine gemeinsame IP-Adresse. Trotzdem ist eine große Sammlung von IP-Adressen eine wichtige Basis für deine Datenbank, die damit intelligent Zusammenhänge und Querverbindung zwischen den Datensätzen herstellen kann.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/ipadresse_s1.png",
    "sprite_img": "img/tokens/ipadresse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/ipadresse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/ipadresse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/ipadresse-hover_s1.png",
    "sprite_img_down": "img/tokens/ipadresse-down_s1.png",
    "sprite_img_hover": "img/tokens/ipadresse-hover_s1.png",
    "sprite_img_drag": "img/tokens/ipadresse-drag_s1.png"
  },
  {
    "x": 1319,
    "y": 453,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "politischeeinstellung",
    "label": "Politische\nEinstellung",
    "title": "Politische Einstellung",
    "stats_text": "haben wir Hinweise auf ihre politische Einstellung",
    "origin_stats_text": "erfahren wir Hinweise auf ihre politische Einstellung",
    "description": "Liberal oder konservativ? Links oder rechts? Desinteressiert oder engagiert? Die politische Einstellung ist für viele Menschen prägend und darum ein unverzichtbarer Bestandteil eines ausgewogenen Persönlichkeitsprofils. <br /><br />Und auch wenn staatlicher Spitzel-Terror á la Gestapo oder Stasi in unseren Breiten eher der Vergangenheit angehört - für eine Liste unbequemer, kritischer oder gar \"radikaler\" Namen werden dir die Sicherheitsorgane dankbar sein!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/politischeeinstellung_s1.png",
    "sprite_img": "img/tokens/politischeeinstellung_s1.png",
    "tokenset_img": "img/tokens/tokens_set/politischeeinstellung_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/politischeeinstellung-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/politischeeinstellung-hover_s1.png",
    "sprite_img_down": "img/tokens/politischeeinstellung-down_s1.png",
    "sprite_img_hover": "img/tokens/politischeeinstellung-hover_s1.png",
    "sprite_img_drag": "img/tokens/politischeeinstellung-drag_s1.png"
  }
];
